Added scaling study script

diff --git a/linearElasticity/narrowTmember/AllrunScalingStudy b/linearElasticity/narrowTmember/AllrunScalingStudy
--- a/linearElasticity/narrowTmember/AllrunScalingStudy
+++ b/linearElasticity/narrowTmember/AllrunScalingStudy
@@ -10,34 +10,36 @@ source solids4FoamScripts.sh
 echo "Sourcing the USER_VARIABLE_NAMES file"
 source USER_VARIABLE_NAMES
 
-if [[ -d "${CASE_NAME}.1.${MACHINE}.${SETTINGS}" ]]
+if [[ -d "${CASE_NAME}.${MESH}.RC${RHIECHOWFACTORS[0]}.${MACHINE}.${SETTINGS}" ]]
 then
-    echo "Case ${CASE_NAME}.1.${MACHINE}.${SETTINGS} already exists: please remove it"; echo
+    echo "Case ${CASE_NAME}.${MESH}.RC${RHIECHOWFACTORS[0]}.${MACHINE}.${SETTINGS}
+     already exists: please remove it"; echo
     exit 1;
 fi
-
-# Run cases
-for i in `seq 1 6`;
+ 
+# Loop over RC scaling factor list and perform simulation
+for i in "${RHIECHOWFACTORS[@]}";
 do
-    CASE="${CASE_NAME}.$i.${MACHINE}.${SETTINGS}"
+    CASE="${CASE_NAME}.${MESH}.RC${i}.${MACHINE}.${SETTINGS}"
     echo "Running ${CASE}"
 
     # Copy template case
     cp -r "${BASE}" "${CASE}"
-
+    
     # Enter the case
     cd "${CASE}"
-
+    
+    # Make mesh
     if [ "$USE_GMSH" -eq 1 ]
     then
         # Replace the meshSpacing file
-        if [[ ! -f "meshes/meshSpacing$i.geo" ]]
+        if [[ ! -f "meshes/meshSpacing$MESH.geo" ]]
         then
-            echo "Cannot find ${CASE}/meshes/meshSpacing$i.geo: please add it to ${BASE}/meshes/"; echo
+            echo "Cannot find ${CASE}/meshes/meshSpacing$MESH.geo: please add it to ${BASE}/meshes/"; echo
             exit 1;
         else
-            echo "Copying ${CASE}/meshes/meshSpacing$i.geo to ${CASE}/meshes/meshSpacing.geo"
-            \cp "meshes/meshSpacing$i.geo" meshes/meshSpacing.geo
+            echo "Copying ${CASE}/meshes/meshSpacing$MESH.geo to ${CASE}/meshes/meshSpacing.geo"
+            \cp "meshes/meshSpacing$MESH.geo" meshes/meshSpacing.geo
         fi
 
         # Create the mesh
@@ -54,7 +56,6 @@ do
             then
                 solids4Foam::runApplication polyDualMesh 30 -overwrite
                 solids4Foam::runApplication combinePatchFaces 45 -overwrite
-                #solids4Foam::runApplication changeDictionary
             fi
 
             # Move 0 back
@@ -65,19 +66,28 @@ do
         fi
     else
         # Replace the blockMeshDict
-        if [[ ! -f "system/blockMeshDict.$i" ]]
+        if [[ ! -f "system/blockMeshDict.$MESH" ]]
         then
-            echo "Cannot find ${CASE}/system/blockMeshDict.$i: please add it to ${BASE}/meshes/"; echo
+            echo "Cannot find ${CASE}/system/blockMeshDict.$MESH: please add it to ${BASE}/meshes/"; echo
             exit 1;
         else
-            echo "Copying ${CASE}/system/blockMeshDict.$i to ${CASE}/system/blockMeshDict"
-            \cp "system/blockMeshDict.$i" system/blockMeshDict
+            echo "Copying ${CASE}/system/blockMeshDict.$MESH to ${CASE}/system/blockMeshDict"
+            \cp "system/blockMeshDict.$MESH" system/blockMeshDict
         fi
 
         # Create the mesh
         solids4Foam::runApplication blockMesh
     fi
-
+    
+    # Update Rhie-Chow scaling factor in solidProperties dict
+    if grep -q "scaleFactor" constant/solidProperties;
+    then
+        sed -i "s/scaleFactor.*/scaleFactor  ${i};/" constant/solidProperties
+    else
+        echo "Cannot find stabilisation subdict in ${CASE}/constant/solidProperties. Please add it."; echo
+        exit 1;
+    fi
+    
     # Run the solver
     # If "gtime" is available (/usr/bin/time on Linux), use it to
     # record the max memory usage. On linux gtime is set to be alias for /usr/bin/time
@@ -97,9 +107,11 @@ do
     fi
 
     # Navigate back to the parent directory
-    cd ..
-done
+    cd ..    
+
+done 
 
 echo; echo "Done"; echo
 
-echo "Run ./AllpostMeshStudy to extract the results"; echo
+echo "Run ./AllpostScalingStudy to extract the results"; echo
+
