manufacturedSolution: add structured polyhedra results

diff --git a/linearElasticity/manufacturedSolution/AllrunMeshStudy b/linearElasticity/manufacturedSolution/AllrunMeshStudy
--- a/linearElasticity/manufacturedSolution/AllrunMeshStudy
+++ b/linearElasticity/manufacturedSolution/AllrunMeshStudy
@@ -28,18 +28,55 @@ do
     # Enter the case
     cd "${CASE}"
 
-    # Replace the blockMeshDict
-    if [[ ! -f "system/blockMeshDict.$i" ]]
+    if [ "$USE_GMSH" -eq 1 ]
     then
-        echo "Cannot find ${CASE}/system/blockMeshDict.$i: please add it to ${BASE}/meshes/"; echo
-        exit 1;
-    else
-        echo "Copying ${CASE}/system/blockMeshDict.$i to ${CASE}/system/blockMeshDict"
-        \cp "system/blockMeshDict.$i" system/blockMeshDict
-    fi
+        # Replace the meshSpacing file
+        if [[ ! -f "meshes/meshSpacing$i.geo" ]]
+        then
+            echo "Cannot find ${CASE}/meshes/meshSpacing$i.geo: please add it to ${BASE}/meshes/"; echo
+            exit 1;
+        else
+            echo "Copying ${CASE}/meshes/meshSpacing$i.geo to ${CASE}/meshes/meshSpacing.geo"
+            \cp "meshes/meshSpacing$i.geo" meshes/meshSpacing.geo
+        fi
 
-    # Create the mesh
-    solids4Foam::runApplication blockMesh
+        # Create the mesh
+        if command -v gmsh &> /dev/null
+        then
+            # Remporarily rename 0 to avoid issues
+            mv 0 0.tmp
+
+            # Create mesh with gmsh
+            solids4Foam::runApplication gmsh -3 -format msh2 meshes/cube.geo
+            solids4Foam::runApplication gmshToFoam meshes/cube.msh
+            solids4Foam::runApplication createPatch -overwrite
+            if [ "$USE_POLYDUALMESH" -eq 1 ]
+            then
+                solids4Foam::runApplication polyDualMesh 30 -overwrite
+                solids4Foam::runApplication combinePatchFaces 45 -overwrite
+                #solids4Foam::runApplication changeDictionary
+            fi
+
+            # Move 0 back
+            mv 0.tmp 0
+        else
+            echo; echo "Gmsh is required to run this case: please install it"
+            exit 1
+        fi
+    else
+        # Replace the blockMeshDict
+        if [[ ! -f "system/blockMeshDict.$i" ]]
+        then
+            echo "Cannot find ${CASE}/system/blockMeshDict.$i: please add it to ${BASE}/meshes/"; echo
+            exit 1;
+        else
+            echo "Copying ${CASE}/system/blockMeshDict.$i to ${CASE}/system/blockMeshDict"
+            \cp "system/blockMeshDict.$i" system/blockMeshDict
+        fi
+
+        # Create the mesh
+        solids4Foam::runApplication blockMesh
+    fi
 
     # Run the solver
     # If "gtime" is available (could be called "time" on Linux), use it to
